### ISSUE TITLE
主页滑动横幅后刷新闪退

### ISSUE THREAD

**Issue by lqaqlaaa** [fumiama/copymanga#65]
![Screenshot_2024-04-13-09-33-25-816_top fumiama copymanga-edit](https://github.com/fumiama/copymanga/assets/107952122/6a1a3acb-a637-47bf-8285-a83db0d0bece)
这个横幅任意左右滑动一次，然后下拉刷新应用就会闪退

**Comment by fumiama** [comment]
无法复现。

**Comment by lqaqlaaa** [comment]
![Screenshot_2024-04-13-16-04-14-961_top fumiama copymanga](https://github.com/fumiama/copymanga/assets/107952122/f938ec6b-0064-4870-970c-0b216b78699f)
默认刚进去，界面是这样，这时候滑动一下他的横幅，它底下的内容会改变。如果等他全部加载完，似乎就不会闪退，但如果是滑动以后他改变你刷新他就闪退了

**Comment by lqaqlaaa** [comment]
https://github.com/fumiama/copymanga/assets/107952122/3a251a4b-cf9a-4c91-b6c4-3683c4dfd984

**Comment by fumiama** [comment]
你可查看日志并粘贴上来。

**Comment by lqaqlaaa** [comment]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10188)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2085)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(Unknown Source:4)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(SourceFile:4)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at androidx.core.widget.NestedScrollView.requestLayout(Unknown Source:3)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:26479)
	at android.view.View.requestLayout(View.java:26479)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(Unknown Source:8)
	at androidx.recyclerview.widget.e1.onChanged(Unknown Source:22)
	at androidx.recyclerview.widget.j0.b(SourceFile:1)
	at androidx.recyclerview.widget.i0.notifyDataSetChanged(Unknown Source:2)
	at com.to.aboomy.pager2banner.Banner.startPager(Unknown Source:13)
	at com.to.aboomy.pager2banner.Banner.access$1400(Unknown Source:0)
	at com.to.aboomy.pager2banner.Banner$2.onChanged(Unknown Source:6)
	at androidx.recyclerview.widget.j0.b(SourceFile:1)
	at androidx.recyclerview.widget.i0.notifyDataSetChanged(Unknown Source:2)
	at h7.m0.j(SourceFile:74)
	at k5.a.f(SourceFile:1)
	at z5.c0.run(SourceFile:1)
	at l.j.run(SourceFile:14)
	at e6.i.run(SourceFile:1)
	at e6.a.run(SourceFile:92)
	Suppressed: d6.d: [f1{Cancelling}@980f6f1, Dispatchers.Main.immediate]

**Comment by fumiama** [comment]
OK, 明白了, 下版修复。
