### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by RX93CN** [fumiama/copymanga#81]
在域名为mangacopy.com时，可连接拷贝的网络以及挂全局梯子的情况下，直接闪退，设备是mi12

**Comment by RX93CN** [comment]
以下为手机自带三方应用分析的报错信息
java.lang.IllegalArgumentException: Must not be null or empty
	at b1.s.<init>(SourceFile:7)
	at d3.n.onBindViewHolder(SourceFile:381)
	at com.to.aboomy.pager2banner.Banner$BannerAdapterWrapper.onBindViewHolder(Unknown Source:8)
	at androidx.recyclerview.widget.I.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.I.bindViewHolder(SourceFile:34)
	at androidx.recyclerview.widget.d0.j(SourceFile:1063)
	at androidx.recyclerview.widget.y.b(SourceFile:63)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:840)
	at androidx.recyclerview.widget.RecyclerView.d(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:31)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at androidx.core.widget.NestedScrollView.onLayout(SourceFile:1)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:61)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at v1.e.x(SourceFile:144)
	at v1.f.l(SourceFile:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:41)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(SourceFile:58)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:852)
	at android.view.View.layout(View.java:25222)
	at android.view.ViewGroup.layout(ViewGroup.java:6515)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4780)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4089)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10188)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1623)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1632)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1602)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by mikeyshells** [comment]
小米，澎湃OS 1.0.5，同样的报错，联网进入目前100%闪退，开飞行模式断网进入不会闪退，推测是不是目前首页展示的某个特定内容导致的。
